-- Categorias
INSERT INTO tb_category (name, created_at) VALUES ('discos', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('livros', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('computadores', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('eletrônicos', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('dvds', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('cds', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('games', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('roupas', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('calçados', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('móveis', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('decoração', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('esportes', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('instrumentos musicais', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('filmes', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('celulares', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('smartwatches', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('televisores', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('notebooks', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('câmeras', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('periféricos', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('hardware', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('softwares', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('automotivo', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('bicicletas', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('ferramentas', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('jardinagem', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('cozinha', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('bebês', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('brinquedos', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('petshop', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('cosméticos', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('cama mesa e banho', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('papelaria', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('acessórios', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('relógios', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('óculos', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('bolsas', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('malas e mochilas', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('viagem', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('segurança', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('iluminação', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('energia solar', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('papel de parede', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('tintas', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('reformas', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('material de construção', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('pneus', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('som automotivo', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('gps', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('camping', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('pesca', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('fitness', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('nutrição esportiva', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('moda masculina', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('moda feminina', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('moda infantil', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('lingerie', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('fantasias', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('artesanato', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('colecionáveis', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('quadrinhos', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('mangás', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('animes', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('action figures', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('board games', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('bar e adega', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('vinhos', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('cervejas artesanais', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('refeições congeladas', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('delivery', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('produtos orgânicos', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('livros técnicos', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('romances', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('autoajuda', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('biografias', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('ebooks', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('revistas', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('jornais', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('filmes clássicos', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('lançamentos', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('blu-ray', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('box colecionador', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('teatro', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('eventos', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('ingressos', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('streaming', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('podcasts', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('aulas online', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('cursos técnicos', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('universitários', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('idiomas', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('concursos', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('vestibular', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('reforço escolar', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('profissionalizantes', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('pós-graduação', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('livros infantis', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('jogos de tabuleiro', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('puzzles', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('figurinhas', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('moedas e selos', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('modelismo', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('drones', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('robótica', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('ciência e tecnologia', NOW());